# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# ruff: noqa: F401, PLR0912, PLR0913, PLR0914, PLR0915, PLR0917, RUF100

import math
import typing as T

import numpy

import sym


def extrinsics_projection_with_jacobians0123456(
    sym_P_ins,
    sym_E,
    sym_skew,
    sym_focal_length,
    sym_principal_point,
    sym_distortion_params,
    sym_W_gcp,
    sym_measurement,
):
    # type: (sym.Pose3, sym.Pose3, float, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray) -> T.Tuple[numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray]
    """
    This function was autogenerated from a symbolic function. Do not modify by hand.

    Symbolic function: extrinsics_projection

    Args:
        sym_P_ins: Pose3
        sym_E: Pose3
        sym_skew: Scalar
        sym_focal_length: Matrix21
        sym_principal_point: Matrix21
        sym_distortion_params: Matrix41
        sym_W_gcp: Matrix31
        sym_measurement: Matrix21

    Outputs:
        res: Matrix21
        res_D_sym_P_ins: (2x6) jacobian of res (2) wrt arg sym_P_ins (6)
        res_D_sym_E: (2x6) jacobian of res (2) wrt arg sym_E (6)
        res_D_sym_skew: (2x1) jacobian of res (2) wrt arg sym_skew (1)
        res_D_sym_focal_length: (2x2) jacobian of res (2) wrt arg sym_focal_length (2)
        res_D_sym_principal_point: (2x2) jacobian of res (2) wrt arg sym_principal_point (2)
        res_D_sym_distortion_params: (2x4) jacobian of res (2) wrt arg sym_distortion_params (4)
        res_D_sym_W_gcp: (2x3) jacobian of res (2) wrt arg sym_W_gcp (3)
    """

    # Total ops: 1438

    # Input arrays
    _sym_P_ins = sym_P_ins.data
    _sym_E = sym_E.data
    if sym_focal_length.shape == (2,):
        sym_focal_length = sym_focal_length.reshape((2, 1))
    elif sym_focal_length.shape != (2, 1):
        raise IndexError(
            "sym_focal_length is expected to have shape (2, 1) or (2,); instead had shape {}".format(
                sym_focal_length.shape
            )
        )

    if sym_principal_point.shape == (2,):
        sym_principal_point = sym_principal_point.reshape((2, 1))
    elif sym_principal_point.shape != (2, 1):
        raise IndexError(
            "sym_principal_point is expected to have shape (2, 1) or (2,); instead had shape {}".format(
                sym_principal_point.shape
            )
        )

    if sym_distortion_params.shape == (4,):
        sym_distortion_params = sym_distortion_params.reshape((4, 1))
    elif sym_distortion_params.shape != (4, 1):
        raise IndexError(
            "sym_distortion_params is expected to have shape (4, 1) or (4,); instead had shape {}".format(
                sym_distortion_params.shape
            )
        )

    if sym_W_gcp.shape == (3,):
        sym_W_gcp = sym_W_gcp.reshape((3, 1))
    elif sym_W_gcp.shape != (3, 1):
        raise IndexError(
            "sym_W_gcp is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                sym_W_gcp.shape
            )
        )

    if sym_measurement.shape == (2,):
        sym_measurement = sym_measurement.reshape((2, 1))
    elif sym_measurement.shape != (2, 1):
        raise IndexError(
            "sym_measurement is expected to have shape (2, 1) or (2,); instead had shape {}".format(
                sym_measurement.shape
            )
        )

    # Intermediate terms (463)
    _tmp0 = _sym_E[3] * _sym_P_ins[2]
    _tmp1 = _sym_E[1] * _sym_P_ins[0]
    _tmp2 = _sym_E[2] * _sym_P_ins[3]
    _tmp3 = _sym_E[0] * _sym_P_ins[1]
    _tmp4 = _tmp0 + _tmp1 + _tmp2 - _tmp3
    _tmp5 = -2 * _tmp4**2
    _tmp6 = _sym_E[0] * _sym_P_ins[2]
    _tmp7 = _sym_E[2] * _sym_P_ins[0]
    _tmp8 = _sym_E[1] * _sym_P_ins[3]
    _tmp9 = _sym_E[3] * _sym_P_ins[1]
    _tmp10 = _tmp6 - _tmp7 + _tmp8 + _tmp9
    _tmp11 = -2 * _tmp10**2
    _tmp12 = _tmp11 + _tmp5 + 1
    _tmp13 = _sym_P_ins[2] ** 2
    _tmp14 = 2 * _tmp13
    _tmp15 = -_tmp14
    _tmp16 = _sym_P_ins[1] ** 2
    _tmp17 = 2 * _tmp16
    _tmp18 = -_tmp17
    _tmp19 = 2 * _sym_P_ins[0]
    _tmp20 = _sym_P_ins[2] * _tmp19
    _tmp21 = 2 * _sym_P_ins[3]
    _tmp22 = _sym_P_ins[1] * _tmp21
    _tmp23 = _tmp20 + _tmp22
    _tmp24 = _sym_P_ins[1] * _tmp19
    _tmp25 = _sym_P_ins[2] * _tmp21
    _tmp26 = -_tmp25
    _tmp27 = _tmp24 + _tmp26
    _tmp28 = (
        -_sym_E[4] * (_tmp15 + _tmp18 + 1)
        - _sym_E[5] * _tmp27
        - _sym_E[6] * _tmp23
        - _sym_P_ins[4]
        + sym_W_gcp[0, 0]
    )
    _tmp29 = _sym_E[1] * _sym_P_ins[2]
    _tmp30 = _sym_E[3] * _sym_P_ins[0]
    _tmp31 = _sym_E[0] * _sym_P_ins[3]
    _tmp32 = _sym_E[2] * _sym_P_ins[1]
    _tmp33 = -_tmp29 + _tmp30 + _tmp31 + _tmp32
    _tmp34 = 2 * _tmp10
    _tmp35 = _tmp33 * _tmp34
    _tmp36 = _sym_E[2] * _sym_P_ins[2]
    _tmp37 = _sym_E[0] * _sym_P_ins[0]
    _tmp38 = _sym_E[1] * _sym_P_ins[1]
    _tmp39 = _sym_E[3] * _sym_P_ins[3]
    _tmp40 = -_tmp36 - _tmp37 - _tmp38 + _tmp39
    _tmp41 = 2 * _tmp4
    _tmp42 = _tmp40 * _tmp41
    _tmp43 = _tmp35 + _tmp42
    _tmp44 = _sym_P_ins[0] ** 2
    _tmp45 = 2 * _tmp44
    _tmp46 = 1 - _tmp45
    _tmp47 = _tmp24 + _tmp25
    _tmp48 = 2 * _sym_P_ins[1] * _sym_P_ins[2]
    _tmp49 = _sym_P_ins[3] * _tmp19
    _tmp50 = -_tmp49
    _tmp51 = _tmp48 + _tmp50
    _tmp52 = (
        -_sym_E[4] * _tmp47
        - _sym_E[5] * (_tmp15 + _tmp46)
        - _sym_E[6] * _tmp51
        - _sym_P_ins[5]
        + sym_W_gcp[1, 0]
    )
    _tmp53 = _tmp33 * _tmp41
    _tmp54 = _tmp34 * _tmp40
    _tmp55 = _tmp53 - _tmp54
    _tmp56 = -_tmp22
    _tmp57 = _tmp20 + _tmp56
    _tmp58 = _tmp48 + _tmp49
    _tmp59 = (
        -_sym_E[4] * _tmp57
        - _sym_E[5] * _tmp58
        - _sym_E[6] * (_tmp18 + _tmp46)
        - _sym_P_ins[6]
        + sym_W_gcp[2, 0]
    )
    _tmp60 = _tmp12 * _tmp28 + _tmp43 * _tmp52 + _tmp55 * _tmp59
    _tmp61 = _tmp34 * _tmp4
    _tmp62 = 2 * _tmp33
    _tmp63 = _tmp40 * _tmp62
    _tmp64 = _tmp61 - _tmp63
    _tmp65 = _tmp53 + _tmp54
    _tmp66 = 1 - 2 * _tmp33**2
    _tmp67 = _tmp11 + _tmp66
    _tmp68 = _tmp28 * _tmp65 + _tmp52 * _tmp64 + _tmp59 * _tmp67
    _tmp69 = _tmp68 ** (-2)
    _tmp70 = _tmp61 + _tmp63
    _tmp71 = _tmp35 - _tmp42
    _tmp72 = _tmp5 + _tmp66
    _tmp73 = _tmp28 * _tmp71 + _tmp52 * _tmp72 + _tmp59 * _tmp70
    _tmp74 = _tmp69 * _tmp73
    _tmp75 = 2 * _tmp74
    _tmp76 = _tmp75 * sym_distortion_params[2, 0]
    _tmp77 = _tmp60**2
    _tmp78 = _tmp69 * _tmp77
    _tmp79 = _tmp73**2
    _tmp80 = _tmp69 * _tmp79
    _tmp81 = 3 * _tmp78 + _tmp80
    _tmp82 = 1 / _tmp68
    _tmp83 = _tmp78 + _tmp80
    _tmp84 = _tmp83**2
    _tmp85 = _tmp83 * sym_distortion_params[0, 0] + _tmp84 * sym_distortion_params[1, 0] + 1
    _tmp86 = _tmp82 * _tmp85
    _tmp87 = _tmp60 * _tmp76 + _tmp60 * _tmp86 + _tmp81 * sym_distortion_params[3, 0]
    _tmp88 = _tmp60 * _tmp75
    _tmp89 = _tmp73 * _tmp82
    _tmp90 = _tmp78 + 3 * _tmp80
    _tmp91 = (
        _tmp85 * _tmp89
        + _tmp88 * sym_distortion_params[3, 0]
        + _tmp90 * sym_distortion_params[2, 0]
    )
    _tmp92 = (1.0 / 2.0) * _tmp37
    _tmp93 = -_tmp92
    _tmp94 = (1.0 / 2.0) * _tmp38
    _tmp95 = (1.0 / 2.0) * _tmp36
    _tmp96 = (1.0 / 2.0) * _tmp39
    _tmp97 = _tmp95 + _tmp96
    _tmp98 = _tmp93 + _tmp94 + _tmp97
    _tmp99 = 4 * _tmp33
    _tmp100 = -_tmp98 * _tmp99
    _tmp101 = (1.0 / 2.0) * _tmp7
    _tmp102 = -_tmp101
    _tmp103 = (1.0 / 2.0) * _tmp8
    _tmp104 = _tmp102 + _tmp103
    _tmp105 = (1.0 / 2.0) * _tmp9
    _tmp106 = -_tmp105
    _tmp107 = (1.0 / 2.0) * _tmp6
    _tmp108 = -_tmp107
    _tmp109 = _tmp106 + _tmp108
    _tmp110 = _tmp104 + _tmp109
    _tmp111 = 4 * _tmp4
    _tmp112 = -_tmp110 * _tmp111
    _tmp113 = (1.0 / 2.0) * _tmp32
    _tmp114 = (1.0 / 2.0) * _tmp30
    _tmp115 = -_tmp114
    _tmp116 = (1.0 / 2.0) * _tmp29
    _tmp117 = -_tmp116
    _tmp118 = (1.0 / 2.0) * _tmp31
    _tmp119 = -_tmp118
    _tmp120 = _tmp117 + _tmp119
    _tmp121 = _tmp113 + _tmp115 + _tmp120
    _tmp122 = _tmp121 * _tmp62
    _tmp123 = 2 * _tmp40
    _tmp124 = _tmp123 * _tmp98
    _tmp125 = (1.0 / 2.0) * _tmp0
    _tmp126 = (1.0 / 2.0) * _tmp2
    _tmp127 = -_tmp126
    _tmp128 = (1.0 / 2.0) * _tmp1
    _tmp129 = -_tmp128
    _tmp130 = (1.0 / 2.0) * _tmp3
    _tmp131 = -_tmp130
    _tmp132 = _tmp129 + _tmp131
    _tmp133 = _tmp125 + _tmp127 + _tmp132
    _tmp134 = _tmp110 * _tmp34 + _tmp133 * _tmp41
    _tmp135 = -_tmp24
    _tmp136 = _tmp135 + _tmp25
    _tmp137 = -_sym_E[5] * _tmp23 - _sym_E[6] * _tmp136
    _tmp138 = _tmp121 * _tmp41
    _tmp139 = _tmp110 * _tmp123
    _tmp140 = _tmp133 * _tmp62 + _tmp34 * _tmp98
    _tmp141 = -_tmp44
    _tmp142 = _sym_P_ins[3] ** 2
    _tmp143 = -_tmp16
    _tmp144 = -_tmp48
    _tmp145 = _tmp144 + _tmp50
    _tmp146 = -_sym_E[5] * (_tmp13 + _tmp141 + _tmp142 + _tmp143) - _sym_E[6] * _tmp145
    _tmp147 = -_tmp142
    _tmp148 = _tmp13 + _tmp147
    _tmp149 = _tmp143 + _tmp44
    _tmp150 = -_sym_E[5] * _tmp51 - _sym_E[6] * (_tmp148 + _tmp149)
    _tmp151 = (
        _tmp137 * _tmp71
        + _tmp146 * _tmp70
        + _tmp150 * _tmp72
        + _tmp28 * (-_tmp138 - _tmp139 + _tmp140)
        + _tmp52 * (_tmp100 + _tmp112)
        + _tmp59 * (_tmp122 + _tmp124 + _tmp134)
    )
    _tmp152 = _tmp60 * _tmp69
    _tmp153 = 2 * _tmp152
    _tmp154 = _tmp151 * _tmp153
    _tmp155 = _tmp121 * _tmp34
    _tmp156 = _tmp123 * _tmp133
    _tmp157 = _tmp110 * _tmp62 + _tmp41 * _tmp98
    _tmp158 = 4 * _tmp10
    _tmp159 = -_tmp133 * _tmp158
    _tmp160 = (
        _tmp12 * _tmp137
        + _tmp146 * _tmp55
        + _tmp150 * _tmp43
        + _tmp28 * (_tmp112 + _tmp159)
        + _tmp52 * (_tmp138 + _tmp139 + _tmp140)
        + _tmp59 * (-_tmp155 - _tmp156 + _tmp157)
    )
    _tmp161 = (
        _tmp137 * _tmp65
        + _tmp146 * _tmp67
        + _tmp150 * _tmp64
        + _tmp28 * (_tmp155 + _tmp156 + _tmp157)
        + _tmp52 * (-_tmp122 - _tmp124 + _tmp134)
        + _tmp59 * (_tmp100 + _tmp159)
    )
    _tmp162 = _tmp152 * _tmp85
    _tmp163 = _tmp68 ** (-3)
    _tmp164 = 4 * _tmp163 * _tmp60 * _tmp73
    _tmp165 = _tmp164 * sym_distortion_params[2, 0]
    _tmp166 = _tmp163 * _tmp77
    _tmp167 = 6 * _tmp166
    _tmp168 = 6 * _tmp152
    _tmp169 = _tmp163 * _tmp79
    _tmp170 = 2 * _tmp169
    _tmp171 = _tmp151 * _tmp75 - _tmp161 * _tmp170
    _tmp172 = 2 * _tmp166
    _tmp173 = _tmp153 * _tmp160 - _tmp161 * _tmp172
    _tmp174 = _tmp171 + _tmp173
    _tmp175 = 2 * _tmp83 * sym_distortion_params[1, 0]
    _tmp176 = _tmp174 * _tmp175 + _tmp174 * sym_distortion_params[0, 0]
    _tmp177 = _tmp60 * _tmp82
    _tmp178 = _tmp75 * sym_distortion_params[3, 0]
    _tmp179 = _tmp74 * _tmp85
    _tmp180 = _tmp164 * sym_distortion_params[3, 0]
    _tmp181 = 6 * _tmp169
    _tmp182 = 6 * _tmp74
    _tmp183 = (
        _tmp151 * _tmp86
        + _tmp154 * sym_distortion_params[3, 0]
        + _tmp160 * _tmp178
        - _tmp161 * _tmp179
        - _tmp161 * _tmp180
        + _tmp176 * _tmp89
        + sym_distortion_params[2, 0] * (_tmp151 * _tmp182 - _tmp161 * _tmp181 + _tmp173)
    )
    _tmp184 = -_tmp125
    _tmp185 = _tmp126 + _tmp132 + _tmp184
    _tmp186 = -_tmp185 * _tmp99
    _tmp187 = -_tmp113
    _tmp188 = _tmp114 + _tmp120 + _tmp187
    _tmp189 = -_tmp111 * _tmp188
    _tmp190 = _tmp144 + _tmp49
    _tmp191 = -_sym_E[4] * _tmp190 - _sym_E[6] * _tmp47
    _tmp192 = -_tmp103
    _tmp193 = _tmp102 + _tmp192
    _tmp194 = _tmp106 + _tmp107 + _tmp193
    _tmp195 = _tmp194 * _tmp62
    _tmp196 = _tmp123 * _tmp185
    _tmp197 = -_tmp94
    _tmp198 = _tmp197 + _tmp92 + _tmp97
    _tmp199 = _tmp188 * _tmp34 + _tmp198 * _tmp41
    _tmp200 = _tmp194 * _tmp41
    _tmp201 = _tmp123 * _tmp188
    _tmp202 = _tmp185 * _tmp34 + _tmp198 * _tmp62
    _tmp203 = -_tmp13
    _tmp204 = -_sym_E[4] * (_tmp147 + _tmp16 + _tmp203 + _tmp44) - _sym_E[6] * _tmp57
    _tmp205 = _tmp142 + _tmp203
    _tmp206 = -_tmp20
    _tmp207 = _tmp206 + _tmp56
    _tmp208 = -_sym_E[4] * _tmp207 - _sym_E[6] * (_tmp149 + _tmp205)
    _tmp209 = (
        _tmp191 * _tmp72
        + _tmp204 * _tmp70
        + _tmp208 * _tmp71
        + _tmp28 * (-_tmp200 - _tmp201 + _tmp202)
        + _tmp52 * (_tmp186 + _tmp189)
        + _tmp59 * (_tmp195 + _tmp196 + _tmp199)
    )
    _tmp210 = _tmp194 * _tmp34
    _tmp211 = _tmp123 * _tmp198
    _tmp212 = _tmp185 * _tmp41 + _tmp188 * _tmp62
    _tmp213 = -_tmp158 * _tmp198
    _tmp214 = (
        _tmp191 * _tmp64
        + _tmp204 * _tmp67
        + _tmp208 * _tmp65
        + _tmp28 * (_tmp210 + _tmp211 + _tmp212)
        + _tmp52 * (-_tmp195 - _tmp196 + _tmp199)
        + _tmp59 * (_tmp186 + _tmp213)
    )
    _tmp215 = _tmp166 * _tmp214
    _tmp216 = (
        _tmp12 * _tmp208
        + _tmp191 * _tmp43
        + _tmp204 * _tmp55
        + _tmp28 * (_tmp189 + _tmp213)
        + _tmp52 * (_tmp200 + _tmp201 + _tmp202)
        + _tmp59 * (-_tmp210 - _tmp211 + _tmp212)
    )
    _tmp217 = 2 * _tmp216
    _tmp218 = _tmp152 * _tmp217 - 2 * _tmp215
    _tmp219 = _tmp217 * _tmp74
    _tmp220 = -_tmp170 * _tmp214 + _tmp209 * _tmp75
    _tmp221 = _tmp218 + _tmp220
    _tmp222 = _tmp175 * _tmp221 + _tmp221 * sym_distortion_params[0, 0]
    _tmp223 = _tmp153 * sym_distortion_params[3, 0]
    _tmp224 = (
        -_tmp179 * _tmp214
        - _tmp180 * _tmp214
        + _tmp209 * _tmp223
        + _tmp209 * _tmp86
        + _tmp219 * sym_distortion_params[3, 0]
        + _tmp222 * _tmp89
        + sym_distortion_params[2, 0] * (-_tmp181 * _tmp214 + _tmp182 * _tmp209 + _tmp218)
    )
    _tmp225 = _tmp153 * sym_distortion_params[2, 0]
    _tmp226 = _tmp127 + _tmp184
    _tmp227 = _tmp128 + _tmp131
    _tmp228 = _tmp226 + _tmp227
    _tmp229 = _tmp228 * _tmp34
    _tmp230 = _tmp117 + _tmp118
    _tmp231 = _tmp115 + _tmp187
    _tmp232 = _tmp230 + _tmp231
    _tmp233 = _tmp123 * _tmp232
    _tmp234 = -_tmp95 + _tmp96
    _tmp235 = _tmp234 + _tmp92 + _tmp94
    _tmp236 = _tmp105 + _tmp108 + _tmp193
    _tmp237 = _tmp235 * _tmp62 + _tmp236 * _tmp41
    _tmp238 = -_tmp158 * _tmp232
    _tmp239 = -_tmp111 * _tmp235
    _tmp240 = _tmp141 + _tmp16
    _tmp241 = -_sym_E[4] * _tmp27 - _sym_E[5] * (_tmp148 + _tmp240)
    _tmp242 = _tmp206 + _tmp22
    _tmp243 = -_sym_E[4] * _tmp58 - _sym_E[5] * _tmp242
    _tmp244 = _tmp135 + _tmp26
    _tmp245 = -_sym_E[4] * (_tmp205 + _tmp240) - _sym_E[5] * _tmp244
    _tmp246 = _tmp228 * _tmp41
    _tmp247 = _tmp123 * _tmp235
    _tmp248 = _tmp232 * _tmp62 + _tmp236 * _tmp34
    _tmp249 = (
        _tmp12 * _tmp241
        + _tmp243 * _tmp55
        + _tmp245 * _tmp43
        + _tmp28 * (_tmp238 + _tmp239)
        + _tmp52 * (_tmp246 + _tmp247 + _tmp248)
        + _tmp59 * (-_tmp229 - _tmp233 + _tmp237)
    )
    _tmp250 = -_tmp236 * _tmp99
    _tmp251 = _tmp228 * _tmp62
    _tmp252 = _tmp123 * _tmp236
    _tmp253 = _tmp232 * _tmp41 + _tmp235 * _tmp34
    _tmp254 = (
        _tmp241 * _tmp65
        + _tmp243 * _tmp67
        + _tmp245 * _tmp64
        + _tmp28 * (_tmp229 + _tmp233 + _tmp237)
        + _tmp52 * (-_tmp251 - _tmp252 + _tmp253)
        + _tmp59 * (_tmp238 + _tmp250)
    )
    _tmp255 = _tmp166 * _tmp254
    _tmp256 = _tmp153 * _tmp249 - 2 * _tmp255
    _tmp257 = (
        _tmp241 * _tmp71
        + _tmp243 * _tmp70
        + _tmp245 * _tmp72
        + _tmp28 * (-_tmp246 - _tmp247 + _tmp248)
        + _tmp52 * (_tmp239 + _tmp250)
        + _tmp59 * (_tmp251 + _tmp252 + _tmp253)
    )
    _tmp258 = -_tmp170 * _tmp254 + _tmp257 * _tmp75
    _tmp259 = _tmp256 + _tmp258
    _tmp260 = _tmp175 * _tmp259 + _tmp259 * sym_distortion_params[0, 0]
    _tmp261 = (
        _tmp178 * _tmp249
        - _tmp179 * _tmp254
        - _tmp180 * _tmp254
        + _tmp223 * _tmp257
        + _tmp257 * _tmp86
        + _tmp260 * _tmp89
        + sym_distortion_params[2, 0] * (-_tmp181 * _tmp254 + _tmp182 * _tmp257 + _tmp256)
    )
    _tmp262 = _tmp180 * _tmp65
    _tmp263 = _tmp12 * _tmp178
    _tmp264 = _tmp179 * _tmp65
    _tmp265 = _tmp166 * _tmp65
    _tmp266 = 2 * _tmp265
    _tmp267 = _tmp12 * _tmp153
    _tmp268 = _tmp266 - _tmp267
    _tmp269 = _tmp71 * _tmp75
    _tmp270 = _tmp169 * _tmp65
    _tmp271 = 2 * _tmp270
    _tmp272 = -_tmp269 + _tmp271
    _tmp273 = _tmp268 + _tmp272
    _tmp274 = _tmp175 * _tmp273 + _tmp273 * sym_distortion_params[0, 0]
    _tmp275 = _tmp182 * _tmp71
    _tmp276 = 6 * _tmp270
    _tmp277 = _tmp153 * _tmp71
    _tmp278 = _tmp277 * sym_distortion_params[3, 0]
    _tmp279 = _tmp71 * _tmp86
    _tmp280 = (
        _tmp262
        - _tmp263
        + _tmp264
        + _tmp274 * _tmp89
        - _tmp278
        - _tmp279
        + sym_distortion_params[2, 0] * (_tmp268 - _tmp275 + _tmp276)
    )
    _tmp281 = _tmp165 * _tmp65
    _tmp282 = _tmp12 * _tmp76
    _tmp283 = _tmp12 * _tmp86
    _tmp284 = _tmp162 * _tmp65
    _tmp285 = 6 * _tmp265
    _tmp286 = _tmp12 * _tmp168
    _tmp287 = _tmp277 * sym_distortion_params[2, 0]
    _tmp288 = _tmp72 * _tmp75
    _tmp289 = _tmp170 * _tmp64
    _tmp290 = -_tmp288 + _tmp289
    _tmp291 = _tmp166 * _tmp64
    _tmp292 = 2 * _tmp291
    _tmp293 = _tmp153 * _tmp43
    _tmp294 = _tmp292 - _tmp293
    _tmp295 = _tmp290 + _tmp294
    _tmp296 = _tmp175 * _tmp295 + _tmp295 * sym_distortion_params[0, 0]
    _tmp297 = _tmp178 * _tmp43
    _tmp298 = _tmp153 * _tmp72
    _tmp299 = _tmp298 * sym_distortion_params[3, 0]
    _tmp300 = _tmp72 * _tmp86
    _tmp301 = _tmp179 * _tmp64
    _tmp302 = _tmp182 * _tmp72
    _tmp303 = _tmp181 * _tmp64
    _tmp304 = _tmp180 * _tmp64
    _tmp305 = (
        _tmp296 * _tmp89
        - _tmp297
        - _tmp299
        - _tmp300
        + _tmp301
        + _tmp304
        + sym_distortion_params[2, 0] * (_tmp294 - _tmp302 + _tmp303)
    )
    _tmp306 = _tmp162 * _tmp64
    _tmp307 = _tmp43 * _tmp76
    _tmp308 = _tmp298 * sym_distortion_params[2, 0]
    _tmp309 = 6 * _tmp291
    _tmp310 = _tmp168 * _tmp43
    _tmp311 = _tmp165 * _tmp64
    _tmp312 = _tmp43 * _tmp86
    _tmp313 = _tmp153 * _tmp70
    _tmp314 = _tmp313 * sym_distortion_params[3, 0]
    _tmp315 = _tmp182 * _tmp70
    _tmp316 = _tmp181 * _tmp67
    _tmp317 = _tmp153 * _tmp55
    _tmp318 = _tmp166 * _tmp67
    _tmp319 = 2 * _tmp318
    _tmp320 = -_tmp317 + _tmp319
    _tmp321 = _tmp179 * _tmp67
    _tmp322 = _tmp70 * _tmp86
    _tmp323 = _tmp178 * _tmp55
    _tmp324 = _tmp180 * _tmp67
    _tmp325 = _tmp70 * _tmp75
    _tmp326 = _tmp170 * _tmp67
    _tmp327 = -_tmp325 + _tmp326
    _tmp328 = _tmp320 + _tmp327
    _tmp329 = _tmp175 * _tmp328 + _tmp328 * sym_distortion_params[0, 0]
    _tmp330 = (
        -_tmp314
        + _tmp321
        - _tmp322
        - _tmp323
        + _tmp324
        + _tmp329 * _tmp89
        + sym_distortion_params[2, 0] * (-_tmp315 + _tmp316 + _tmp320)
    )
    _tmp331 = _tmp313 * sym_distortion_params[2, 0]
    _tmp332 = _tmp168 * _tmp55
    _tmp333 = 6 * _tmp318
    _tmp334 = _tmp162 * _tmp67
    _tmp335 = _tmp55 * _tmp76
    _tmp336 = _tmp165 * _tmp67
    _tmp337 = _tmp55 * _tmp86
    _tmp338 = _tmp116 + _tmp119 + _tmp231
    _tmp339 = _tmp338 * _tmp34
    _tmp340 = _tmp125 + _tmp126 + _tmp227
    _tmp341 = _tmp123 * _tmp340
    _tmp342 = _tmp101 + _tmp109 + _tmp192
    _tmp343 = _tmp342 * _tmp62
    _tmp344 = _tmp197 + _tmp234 + _tmp93
    _tmp345 = _tmp344 * _tmp41
    _tmp346 = _tmp343 + _tmp345
    _tmp347 = -_tmp344 * _tmp99
    _tmp348 = -_tmp158 * _tmp340
    _tmp349 = _tmp338 * _tmp62
    _tmp350 = _tmp123 * _tmp344
    _tmp351 = -_tmp350
    _tmp352 = _tmp34 * _tmp342
    _tmp353 = _tmp340 * _tmp41 + _tmp352
    _tmp354 = (
        _tmp28 * (_tmp339 + _tmp341 + _tmp346)
        + _tmp52 * (-_tmp349 + _tmp351 + _tmp353)
        + _tmp59 * (_tmp347 + _tmp348)
    )
    _tmp355 = -_tmp111 * _tmp342
    _tmp356 = _tmp340 * _tmp62
    _tmp357 = _tmp34 * _tmp344
    _tmp358 = _tmp338 * _tmp41
    _tmp359 = _tmp123 * _tmp342
    _tmp360 = (
        _tmp28 * (_tmp356 + _tmp357 - _tmp358 - _tmp359)
        + _tmp52 * (_tmp347 + _tmp355)
        + _tmp59 * (_tmp349 + _tmp350 + _tmp353)
    )
    _tmp361 = _tmp360 * _tmp74
    _tmp362 = -_tmp170 * _tmp354 + 2 * _tmp361
    _tmp363 = _tmp357 + _tmp358
    _tmp364 = (
        _tmp28 * (_tmp348 + _tmp355)
        + _tmp52 * (_tmp356 + _tmp359 + _tmp363)
        + _tmp59 * (-_tmp339 - _tmp341 + _tmp346)
    )
    _tmp365 = _tmp166 * _tmp354
    _tmp366 = _tmp153 * _tmp364 - 2 * _tmp365
    _tmp367 = _tmp362 + _tmp366
    _tmp368 = _tmp175 * _tmp367 + _tmp367 * sym_distortion_params[0, 0]
    _tmp369 = (
        _tmp178 * _tmp364
        - _tmp179 * _tmp354
        - _tmp180 * _tmp354
        + _tmp223 * _tmp360
        + _tmp360 * _tmp86
        + _tmp368 * _tmp89
        + sym_distortion_params[2, 0] * (-_tmp181 * _tmp354 + 6 * _tmp361 + _tmp366)
    )
    _tmp370 = _tmp129 + _tmp130 + _tmp226
    _tmp371 = -_tmp370 * _tmp99
    _tmp372 = _tmp113 + _tmp114 + _tmp230
    _tmp373 = -_tmp111 * _tmp372
    _tmp374 = _tmp34 * _tmp372
    _tmp375 = _tmp123 * _tmp370
    _tmp376 = _tmp342 * _tmp41
    _tmp377 = _tmp123 * _tmp372
    _tmp378 = _tmp344 * _tmp62
    _tmp379 = _tmp34 * _tmp370
    _tmp380 = _tmp378 + _tmp379
    _tmp381 = (
        _tmp28 * (-_tmp376 - _tmp377 + _tmp380)
        + _tmp52 * (_tmp371 + _tmp373)
        + _tmp59 * (_tmp346 + _tmp374 + _tmp375)
    )
    _tmp382 = _tmp370 * _tmp41
    _tmp383 = _tmp372 * _tmp62 + _tmp382
    _tmp384 = -_tmp158 * _tmp344
    _tmp385 = (
        _tmp28 * (_tmp350 + _tmp352 + _tmp383)
        + _tmp52 * (-_tmp343 + _tmp345 + _tmp374 - _tmp375)
        + _tmp59 * (_tmp371 + _tmp384)
    )
    _tmp386 = (
        _tmp28 * (_tmp373 + _tmp384)
        + _tmp52 * (_tmp376 + _tmp377 + _tmp380)
        + _tmp59 * (_tmp351 - _tmp352 + _tmp383)
    )
    _tmp387 = _tmp166 * _tmp385
    _tmp388 = _tmp153 * _tmp386 - 2 * _tmp387
    _tmp389 = -_tmp170 * _tmp385 + _tmp381 * _tmp75
    _tmp390 = _tmp388 + _tmp389
    _tmp391 = _tmp175 * _tmp390 + _tmp390 * sym_distortion_params[0, 0]
    _tmp392 = (
        _tmp178 * _tmp386
        - _tmp179 * _tmp385
        - _tmp180 * _tmp385
        + _tmp223 * _tmp381
        + _tmp381 * _tmp86
        + _tmp391 * _tmp89
        + sym_distortion_params[2, 0] * (-_tmp181 * _tmp385 + _tmp182 * _tmp381 + _tmp388)
    )
    _tmp393 = _tmp123 * _tmp338
    _tmp394 = _tmp104 + _tmp105 + _tmp107
    _tmp395 = _tmp378 + _tmp394 * _tmp41
    _tmp396 = -_tmp394 * _tmp99
    _tmp397 = -_tmp158 * _tmp338
    _tmp398 = _tmp370 * _tmp62
    _tmp399 = _tmp123 * _tmp394
    _tmp400 = (
        _tmp28 * (_tmp379 + _tmp393 + _tmp395)
        + _tmp52 * (_tmp363 - _tmp398 - _tmp399)
        + _tmp59 * (_tmp396 + _tmp397)
    )
    _tmp401 = -_tmp111 * _tmp344
    _tmp402 = _tmp34 * _tmp394 + _tmp349
    _tmp403 = (
        _tmp28 * (_tmp397 + _tmp401)
        + _tmp52 * (_tmp350 + _tmp382 + _tmp402)
        + _tmp59 * (-_tmp379 - _tmp393 + _tmp395)
    )
    _tmp404 = (
        _tmp28 * (_tmp351 - _tmp382 + _tmp402)
        + _tmp52 * (_tmp396 + _tmp401)
        + _tmp59 * (_tmp363 + _tmp398 + _tmp399)
    )
    _tmp405 = -_tmp170 * _tmp400 + _tmp404 * _tmp75
    _tmp406 = _tmp403 * _tmp75
    _tmp407 = _tmp153 * _tmp403 - _tmp172 * _tmp400
    _tmp408 = _tmp405 + _tmp407
    _tmp409 = _tmp175 * _tmp408 + _tmp408 * sym_distortion_params[0, 0]
    _tmp410 = _tmp153 * _tmp404
    _tmp411 = _tmp400 * _tmp85
    _tmp412 = (
        -_tmp180 * _tmp400
        + _tmp404 * _tmp86
        + _tmp406 * sym_distortion_params[3, 0]
        + _tmp409 * _tmp89
        + _tmp410 * sym_distortion_params[3, 0]
        - _tmp411 * _tmp74
        + sym_distortion_params[2, 0] * (-_tmp181 * _tmp400 + _tmp182 * _tmp404 + _tmp407)
    )
    _tmp413 = _tmp14 + _tmp17 - 1
    _tmp414 = _tmp242 * _tmp67 + _tmp244 * _tmp64 + _tmp413 * _tmp65
    _tmp415 = _tmp242 * _tmp70 + _tmp244 * _tmp72 + _tmp413 * _tmp71
    _tmp416 = _tmp166 * _tmp414
    _tmp417 = _tmp12 * _tmp413 + _tmp242 * _tmp55 + _tmp244 * _tmp43
    _tmp418 = _tmp152 * _tmp417
    _tmp419 = -2 * _tmp416 + 2 * _tmp418
    _tmp420 = -_tmp170 * _tmp414 + _tmp415 * _tmp75
    _tmp421 = _tmp419 + _tmp420
    _tmp422 = _tmp175 * _tmp421 + _tmp421 * sym_distortion_params[0, 0]
    _tmp423 = (
        _tmp178 * _tmp417
        - _tmp179 * _tmp414
        - _tmp180 * _tmp414
        + _tmp223 * _tmp415
        + _tmp415 * _tmp86
        + _tmp422 * _tmp89
        + sym_distortion_params[2, 0] * (-_tmp181 * _tmp414 + _tmp182 * _tmp415 + _tmp419)
    )
    _tmp424 = _tmp45 - 1
    _tmp425 = _tmp14 + _tmp424
    _tmp426 = _tmp12 * _tmp136 + _tmp145 * _tmp55 + _tmp425 * _tmp43
    _tmp427 = _tmp136 * _tmp65 + _tmp145 * _tmp67 + _tmp425 * _tmp64
    _tmp428 = _tmp136 * _tmp71 + _tmp145 * _tmp70 + _tmp425 * _tmp72
    _tmp429 = -_tmp170 * _tmp427 + _tmp428 * _tmp75
    _tmp430 = _tmp153 * _tmp426 - _tmp172 * _tmp427
    _tmp431 = _tmp429 + _tmp430
    _tmp432 = _tmp175 * _tmp431 + _tmp431 * sym_distortion_params[0, 0]
    _tmp433 = (
        _tmp178 * _tmp426
        - _tmp179 * _tmp427
        - _tmp180 * _tmp427
        + _tmp223 * _tmp428
        + _tmp428 * _tmp86
        + _tmp432 * _tmp89
        + sym_distortion_params[2, 0] * (-_tmp181 * _tmp427 + _tmp182 * _tmp428 + _tmp430)
    )
    _tmp434 = _tmp17 + _tmp424
    _tmp435 = _tmp190 * _tmp64 + _tmp207 * _tmp65 + _tmp434 * _tmp67
    _tmp436 = _tmp166 * _tmp435
    _tmp437 = _tmp12 * _tmp207 + _tmp190 * _tmp43 + _tmp434 * _tmp55
    _tmp438 = _tmp153 * _tmp437 - 2 * _tmp436
    _tmp439 = _tmp190 * _tmp72 + _tmp207 * _tmp71 + _tmp434 * _tmp70
    _tmp440 = _tmp439 * _tmp74
    _tmp441 = -_tmp170 * _tmp435 + 2 * _tmp440
    _tmp442 = _tmp438 + _tmp441
    _tmp443 = _tmp175 * _tmp442 + _tmp442 * sym_distortion_params[0, 0]
    _tmp444 = (
        _tmp178 * _tmp437
        - _tmp179 * _tmp435
        - _tmp180 * _tmp435
        + _tmp223 * _tmp439
        + _tmp439 * _tmp86
        + _tmp443 * _tmp89
        + sym_distortion_params[2, 0] * (-_tmp181 * _tmp435 + _tmp438 + 6 * _tmp440)
    )
    _tmp445 = _tmp89 * sym_skew
    _tmp446 = _tmp177 * sym_focal_length[0, 0]
    _tmp447 = _tmp89 * sym_focal_length[1, 0]
    _tmp448 = _tmp269 - _tmp271
    _tmp449 = -_tmp266 + _tmp267
    _tmp450 = _tmp448 + _tmp449
    _tmp451 = _tmp175 * _tmp450 + _tmp450 * sym_distortion_params[0, 0]
    _tmp452 = (
        -_tmp262
        + _tmp263
        - _tmp264
        + _tmp278
        + _tmp279
        + _tmp451 * _tmp89
        + sym_distortion_params[2, 0] * (_tmp275 - _tmp276 + _tmp449)
    )
    _tmp453 = _tmp288 - _tmp289
    _tmp454 = -_tmp292 + _tmp293
    _tmp455 = _tmp453 + _tmp454
    _tmp456 = _tmp175 * _tmp455 + _tmp455 * sym_distortion_params[0, 0]
    _tmp457 = (
        _tmp297
        + _tmp299
        + _tmp300
        - _tmp301
        - _tmp304
        + _tmp456 * _tmp89
        + sym_distortion_params[2, 0] * (_tmp302 - _tmp303 + _tmp454)
    )
    _tmp458 = _tmp325 - _tmp326
    _tmp459 = _tmp317 - _tmp319
    _tmp460 = _tmp458 + _tmp459
    _tmp461 = _tmp175 * _tmp460 + _tmp460 * sym_distortion_params[0, 0]
    _tmp462 = (
        _tmp314
        - _tmp321
        + _tmp322
        + _tmp323
        - _tmp324
        + _tmp461 * _tmp89
        + sym_distortion_params[2, 0] * (_tmp315 - _tmp316 + _tmp459)
    )

    # Output terms
    _res = numpy.zeros(2)
    _res[0] = (
        _tmp87 * sym_focal_length[0, 0]
        + _tmp91 * sym_skew
        - sym_measurement[0, 0]
        + sym_principal_point[0, 0]
    )
    _res[1] = _tmp91 * sym_focal_length[1, 0] - sym_measurement[1, 0] + sym_principal_point[1, 0]
    _res_D_sym_P_ins = numpy.zeros((2, 6))
    _res_D_sym_P_ins[0, 0] = _tmp183 * sym_skew + sym_focal_length[0, 0] * (
        _tmp154 * sym_distortion_params[2, 0]
        + _tmp160 * _tmp76
        + _tmp160 * _tmp86
        - _tmp161 * _tmp162
        - _tmp161 * _tmp165
        + _tmp176 * _tmp177
        + sym_distortion_params[3, 0] * (_tmp160 * _tmp168 - _tmp161 * _tmp167 + _tmp171)
    )
    _res_D_sym_P_ins[1, 0] = _tmp183 * sym_focal_length[1, 0]
    _res_D_sym_P_ins[0, 1] = _tmp224 * sym_skew + sym_focal_length[0, 0] * (
        -_tmp162 * _tmp214
        - _tmp165 * _tmp214
        + _tmp177 * _tmp222
        + _tmp209 * _tmp225
        + _tmp216 * _tmp86
        + _tmp219 * sym_distortion_params[2, 0]
        + sym_distortion_params[3, 0] * (_tmp168 * _tmp216 - 6 * _tmp215 + _tmp220)
    )
    _res_D_sym_P_ins[1, 1] = _tmp224 * sym_focal_length[1, 0]
    _res_D_sym_P_ins[0, 2] = _tmp261 * sym_skew + sym_focal_length[0, 0] * (
        -_tmp162 * _tmp254
        - _tmp165 * _tmp254
        + _tmp177 * _tmp260
        + _tmp225 * _tmp257
        + _tmp249 * _tmp76
        + _tmp249 * _tmp86
        + sym_distortion_params[3, 0] * (_tmp168 * _tmp249 - 6 * _tmp255 + _tmp258)
    )
    _res_D_sym_P_ins[1, 2] = _tmp261 * sym_focal_length[1, 0]
    _res_D_sym_P_ins[0, 3] = _tmp280 * sym_skew + sym_focal_length[0, 0] * (
        _tmp177 * _tmp274
        + _tmp281
        - _tmp282
        - _tmp283
        + _tmp284
        - _tmp287
        + sym_distortion_params[3, 0] * (_tmp272 + _tmp285 - _tmp286)
    )
    _res_D_sym_P_ins[1, 3] = _tmp280 * sym_focal_length[1, 0]
    _res_D_sym_P_ins[0, 4] = _tmp305 * sym_skew + sym_focal_length[0, 0] * (
        _tmp177 * _tmp296
        + _tmp306
        - _tmp307
        - _tmp308
        + _tmp311
        - _tmp312
        + sym_distortion_params[3, 0] * (_tmp290 + _tmp309 - _tmp310)
    )
    _res_D_sym_P_ins[1, 4] = _tmp305 * sym_focal_length[1, 0]
    _res_D_sym_P_ins[0, 5] = _tmp330 * sym_skew + sym_focal_length[0, 0] * (
        _tmp177 * _tmp329
        - _tmp331
        + _tmp334
        - _tmp335
        + _tmp336
        - _tmp337
        + sym_distortion_params[3, 0] * (_tmp327 - _tmp332 + _tmp333)
    )
    _res_D_sym_P_ins[1, 5] = _tmp330 * sym_focal_length[1, 0]
    _res_D_sym_E = numpy.zeros((2, 6))
    _res_D_sym_E[0, 0] = _tmp369 * sym_skew + sym_focal_length[0, 0] * (
        -_tmp162 * _tmp354
        - _tmp165 * _tmp354
        + _tmp177 * _tmp368
        + _tmp225 * _tmp360
        + _tmp364 * _tmp76
        + _tmp364 * _tmp86
        + sym_distortion_params[3, 0] * (_tmp168 * _tmp364 + _tmp362 - 6 * _tmp365)
    )
    _res_D_sym_E[1, 0] = _tmp369 * sym_focal_length[1, 0]
    _res_D_sym_E[0, 1] = _tmp392 * sym_skew + sym_focal_length[0, 0] * (
        -_tmp162 * _tmp385
        - _tmp165 * _tmp385
        + _tmp177 * _tmp391
        + _tmp225 * _tmp381
        + _tmp386 * _tmp76
        + _tmp386 * _tmp86
        + sym_distortion_params[3, 0] * (_tmp168 * _tmp386 - 6 * _tmp387 + _tmp389)
    )
    _res_D_sym_E[1, 1] = _tmp392 * sym_focal_length[1, 0]
    _res_D_sym_E[0, 2] = _tmp412 * sym_skew + sym_focal_length[0, 0] * (
        -_tmp152 * _tmp411
        - _tmp165 * _tmp400
        + _tmp177 * _tmp409
        + _tmp403 * _tmp86
        + _tmp406 * sym_distortion_params[2, 0]
        + _tmp410 * sym_distortion_params[2, 0]
        + sym_distortion_params[3, 0] * (-_tmp167 * _tmp400 + _tmp168 * _tmp403 + _tmp405)
    )
    _res_D_sym_E[1, 2] = _tmp412 * sym_focal_length[1, 0]
    _res_D_sym_E[0, 3] = _tmp423 * sym_skew + sym_focal_length[0, 0] * (
        -_tmp162 * _tmp414
        - _tmp165 * _tmp414
        + _tmp177 * _tmp422
        + _tmp225 * _tmp415
        + _tmp417 * _tmp76
        + _tmp417 * _tmp86
        + sym_distortion_params[3, 0] * (-6 * _tmp416 + 6 * _tmp418 + _tmp420)
    )
    _res_D_sym_E[1, 3] = _tmp423 * sym_focal_length[1, 0]
    _res_D_sym_E[0, 4] = _tmp433 * sym_skew + sym_focal_length[0, 0] * (
        -_tmp162 * _tmp427
        - _tmp165 * _tmp427
        + _tmp177 * _tmp432
        + _tmp225 * _tmp428
        + _tmp426 * _tmp76
        + _tmp426 * _tmp86
        + sym_distortion_params[3, 0] * (-_tmp167 * _tmp427 + _tmp168 * _tmp426 + _tmp429)
    )
    _res_D_sym_E[1, 4] = _tmp433 * sym_focal_length[1, 0]
    _res_D_sym_E[0, 5] = _tmp444 * sym_skew + sym_focal_length[0, 0] * (
        -_tmp162 * _tmp435
        - _tmp165 * _tmp435
        + _tmp177 * _tmp443
        + _tmp225 * _tmp439
        + _tmp437 * _tmp76
        + _tmp437 * _tmp86
        + sym_distortion_params[3, 0] * (_tmp168 * _tmp437 - 6 * _tmp436 + _tmp441)
    )
    _res_D_sym_E[1, 5] = _tmp444 * sym_focal_length[1, 0]
    _res_D_sym_skew = numpy.zeros(2)
    _res_D_sym_skew[0] = _tmp91
    _res_D_sym_skew[1] = 0
    _res_D_sym_focal_length = numpy.zeros((2, 2))
    _res_D_sym_focal_length[0, 0] = _tmp87
    _res_D_sym_focal_length[1, 0] = 0
    _res_D_sym_focal_length[0, 1] = 0
    _res_D_sym_focal_length[1, 1] = _tmp91
    _res_D_sym_principal_point = numpy.zeros((2, 2))
    _res_D_sym_principal_point[0, 0] = 1
    _res_D_sym_principal_point[1, 0] = 0
    _res_D_sym_principal_point[0, 1] = 0
    _res_D_sym_principal_point[1, 1] = 1
    _res_D_sym_distortion_params = numpy.zeros((2, 4))
    _res_D_sym_distortion_params[0, 0] = _tmp445 * _tmp83 + _tmp446 * _tmp83
    _res_D_sym_distortion_params[1, 0] = _tmp447 * _tmp83
    _res_D_sym_distortion_params[0, 1] = _tmp445 * _tmp84 + _tmp446 * _tmp84
    _res_D_sym_distortion_params[1, 1] = _tmp447 * _tmp84
    _res_D_sym_distortion_params[0, 2] = _tmp88 * sym_focal_length[0, 0] + _tmp90 * sym_skew
    _res_D_sym_distortion_params[1, 2] = _tmp90 * sym_focal_length[1, 0]
    _res_D_sym_distortion_params[0, 3] = _tmp81 * sym_focal_length[0, 0] + _tmp88 * sym_skew
    _res_D_sym_distortion_params[1, 3] = _tmp88 * sym_focal_length[1, 0]
    _res_D_sym_W_gcp = numpy.zeros((2, 3))
    _res_D_sym_W_gcp[0, 0] = _tmp452 * sym_skew + sym_focal_length[0, 0] * (
        _tmp177 * _tmp451
        - _tmp281
        + _tmp282
        + _tmp283
        - _tmp284
        + _tmp287
        + sym_distortion_params[3, 0] * (-_tmp285 + _tmp286 + _tmp448)
    )
    _res_D_sym_W_gcp[1, 0] = _tmp452 * sym_focal_length[1, 0]
    _res_D_sym_W_gcp[0, 1] = _tmp457 * sym_skew + sym_focal_length[0, 0] * (
        _tmp177 * _tmp456
        - _tmp306
        + _tmp307
        + _tmp308
        - _tmp311
        + _tmp312
        + sym_distortion_params[3, 0] * (-_tmp309 + _tmp310 + _tmp453)
    )
    _res_D_sym_W_gcp[1, 1] = _tmp457 * sym_focal_length[1, 0]
    _res_D_sym_W_gcp[0, 2] = _tmp462 * sym_skew + sym_focal_length[0, 0] * (
        _tmp177 * _tmp461
        + _tmp331
        - _tmp334
        + _tmp335
        - _tmp336
        + _tmp337
        + sym_distortion_params[3, 0] * (_tmp332 - _tmp333 + _tmp458)
    )
    _res_D_sym_W_gcp[1, 2] = _tmp462 * sym_focal_length[1, 0]
    return (
        _res,
        _res_D_sym_P_ins,
        _res_D_sym_E,
        _res_D_sym_skew,
        _res_D_sym_focal_length,
        _res_D_sym_principal_point,
        _res_D_sym_distortion_params,
        _res_D_sym_W_gcp,
    )
